[Application]
AllowResizingRectSelection=true
AutoCopyToClipboardNewCaptures=true
AutoHideDocks=false
AutoSaveNewCaptures=true
CaptureOnStartup=false
CloseToTray=false
MinimizeToTray=false
OverwriteFileEnabled=true
RememberLastSaveDirectory=true
SaveDirectory=/home/als/Рабочий стол/Out
SavePosition=true
StartMinimizedToTray=false
TrayIconDefaultActionMode=1
TrayIconNotificationsEnabled=false
UseTabs=false

[ImageGrabber]
CaptureMode=0
ShowMainWindowAfterTakingScreenshotEnabled=true

[Uploader]
UploaderType=1
ConfirmBeforeUpload=false

[UploadScript]
UploadScriptPath=/home/als/.local/bin/ksnip-catbox
CopyOutputToClipboard=true
UploadScriptStoOnStdErr=false